### ISSUE TITLE
First steps of workflow on MathWorks FileExchange

### ISSUE THREAD

**Issue by pwalczysko** [mathworks/Open-Microscopy-Data-MATLAB#1]
Thank you very much for this nice addition 👍 !

Issue:

On the [MathWorks workflow](https://uk.mathworks.com/matlabcentral/fileexchange/156034-open-microscopy-data-matlab), the second step of Get Started is clicking on the ``Open in Matlab ONLINE`` badge. 

For me, that workflow only really works if you are already signed in to Mathworks.
I suppose this might be because my Mathworks account is associated with a licence and this has to be verified by a third party authentication - this unfortunately does not work from the above sign-in page.

Step by step:
1. Click on badge https://matlab.mathworks.com/open/github/v1?repo=mathworks/Open-Microscopy-Data-MATLAB&file=OpenBiologyTutorial 
2. A sign-in page on https://matlab.mathworks.com/open/github/v1?repo=mathworks/Open-Microscopy-Data-MATLAB&file=OpenBiologyTutorial.mlx which asks for your email address. 
3. Put in a valid email address to which a Matlab account is associated
4. Observe that you are on a blank page with no interactivity in your browser now.
5. In a new tab of your browser, go to https://www.mathworks.com/login and log in with the same email address.
6. Go back to https://matlab.mathworks.com/open/github/v1?repo=mathworks/Open-Microscopy-Data-MATLAB&file=OpenBiologyTutorial - this time, as you are already logged in, all works as expected.
7. In a new private window, go to https://matlab.mathworks.com/
8. Put in the same email address again. Observe that you are confronted with a blank page, similarly to Ad 4. above.

I think that steps 7. and 8. are showing that this is a generic Mathworks problem. Nevertheless, I would suggest adding a note about that in the workflow - this note can also make clear that you do need a Mathworks account in first place, which is a missing info imho.

Thank you

Petr

OME Team

**Comment by ShuboChakrabarti** [comment]
Hi Petr,

I cannot reproduce this issue on my end.

- First, clicking on the badge should open a new tab that should take you to a sign in page where you are required to sign in with your MathWorks account that is linked to your MATLAB licenses. Those without MATLAB licenses can create a MathWorks account using any email and will be able to access [MATLAB Online basic (MATLAB and 10 additional toolboxes for 20 hours a month)](https://www.mathworks.com/products/matlab-online/matlab-online-versions.html). One of the additional toolboxes is the Image Processing Toolbox, which means the tutorial can be run by anybody, not just licensed MATLAB users.

- Second, for me I do not get a unresponsive page (your Step 4).

Can you ask somebody else to replicate the issue on your side?
If not, I can connect with you to try and pinpoint the issue. You can reach me at shuboc@mathworks.com

Best,
Shubo

**Comment by ShuboChakrabarti** [comment]
Im going to open a technical support case for you. Did some digging and this might be an issue with your sign-in system.

**Comment by pwalczysko** [comment]
> Im going to open a technical support case for you. Did some digging and this might be an issue with your sign-in system.

Thank you. As I said, I am not blocked, I have a workaround as described above (going via the https://www.mathworks.com/login)
 
As you asked me I have asked my colleague to repeat my workflow, as well as I did myself repeat on my old laptop, this means we have 3 independent repeats. The main features are the same, i.e the https://matlab.mathworks.com/ page does not redirect properly to the authentication of my org.
We were digging a bit in devtools of the browser, and the redirect which should have been navigated to is
https://www.mathworks.com/auth-edu-sp/Login?entityID=https://idp.dundee.ac.uk/shibboleth&target=https://www.mathworks.com/login/verification/edusso/dotcom

**Comment by pwalczysko** [comment]
> this might be an issue with your sign-in system.

Nevertheless, the same sign-in system works just fine if I start on https://www.mathworks.com/login (as opposed to https://matlab.mathworks.com/)

Thanks

**Comment by ShuboChakrabarti** [comment]
yes. for some reason your matlab.mathworks.com login is not redirecting. The workaround is tedious, it would be better to have the redirect function. Ill get someone who looks after SSO logins on the case

**Comment by ShuboChakrabarti** [comment]
Hi Petr, I see that a tech support case is in the works. Can you let me know once that is done so I can close this issue?

**Comment by pwalczysko** [comment]
> Hi Petr, I see that a tech support case is in the works. Can you let me know once that is done so I can close this issue?

We concluded with the support officer that the problem is in our network setup, not in mathworks. Closing. Thank you
