### ISSUE TITLE
Open Microscopy -> IDR wording

### ISSUE THREAD

**Issue by pwalczysko** [mathworks/Open-Microscopy-Data-MATLAB#2]
Suggesting to change the wordings such as 

``Access the data from Open Microscopy`` to ``Access data from Image Data Resource``.
If the main idea of the workflow is that any OMERO server (not just IDR which is based on OMERO) can be accessed like that (I believe this is the case),
then suggesting 

``Access data from an OMERO server, for example IDR``

Thank you

P

**Comment by ShuboChakrabarti** [comment]
Changed the wording as suggested by you. The webread interface which is the low-level call to a RESTful API can be used with any API. However, in this particular tutorial I query the IDR and include URLs for IDR images, so keeping the wording to reflect that.
