### ISSUE TITLE
Code Ocean error

### ISSUE THREAD

**Issue by JanStudnicka** [mathworks/Open-Microscopy-Data-MATLAB#3]
2.2.2024
When trying to use Reproducible Run on Code Ocean I get this error:

Error using webread
The connection to URL
'https://idr.openmicroscopy.org/webgateway/render_image/13966053/' timed out
after 5.000 seconds. The reason is "Waiting for response header". Perhaps the
server is not responding or weboptions.Timeout needs to be set to a higher
value.

Error in OpenBiologyTutorialScript (line 163)
fullImage = webread(thisImageUrl);

**Comment by JanStudnicka** [comment]
After the second run, everything works.

**Comment by ShuboChakrabarti** [comment]
Hi Jan,
I didnt get the error upon running the capsule. Im guessing there could have been a temporary outage at the openmicroscopy webgateway. Closing the issue.
